//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_ERTE_MGI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERTES
    {
        public int Id_erte { get; set; }
        public string Empresa { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_fin { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
